<?php
/**
 *
 * @category   Marketing
 * @package    ConversionBug_EnhancedEcommerce
 * @author     shiv kumar singh <shivam.kumar@conversionbug.com>
 * @website    http://www.conversionbug.com/
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $block ConversionBug\EnhancedEcommerce\Block\EnhancedEcommerce */ ?>
<?php if (!$this->helper('Magento\Cookie\Helper\Cookie')->isUserNotAllowSaveCookie()): ?>
<!-- BEGIN GOOGLE ENHANCED ECOMMERCE CODE -->
<script>
//<![CDATA[
    <?php /* @escapeNotVerified */
    if($block->getHelper()->isEnabled()) {

        echo "ga('require', 'ec', 'ec.js');";
        echo "ga('set', '&cu', '" . $block->getStoreManager()->getStore()->getCurrentCurrency()->getCode() . "');";              // Set tracker currency to current store currency

        echo $block->getCatalogSession()->getProductScript();
        echo $block->getCatalogSession()->getUpsellScript();
        echo $block->getCatalogSession()->getAddToCart();
        echo $block->getCatalogSession()->getCouponApplied();
        echo $block->getCatalogSession()->getProductListScript();
        $block->getCatalogSession()->unsProductScript();
        $block->getCatalogSession()->unsUpsellScript();
        $block->getCatalogSession()->unsAddToCart();
        $block->getCatalogSession()->unsCouponApplied();
        $block->getCatalogSession()->unsProductListScript();
    } ?>
//]]>
</script>
<!-- END GOOGLE ENHANCED ECOMMERCE CODE -->
<?php endif; ?>
